# include all templates in https://gitlab.cern.ch/cms-cactus/ops/auto-devops/-/tree/0.4.32
include:
  - project: cms-cactus/ops/auto-devops
    ref: 0.4.32
    file: presets/blank-slate.yml

stages:
- 🛠️ setup
- 🏗️ build
#- 🐞 test
#- 📦 publish
- 🚀 deploy
#- 💣 cleanup

builder image:
  #image: gitlab-registry.cern.ch/cms-cactus/ops/auto-devops/basics-cc7:tag-0.4.25
  stage: 🛠️ setup
  extends: .auto_devops_docker_builder_autotag_onchange
  variables:
    DOCKERFILE: builder.Dockerfile
    CONTEXT_FOLDER: .gitlab/ci
    NAME: builder
    container: docker

build:RPMs:
  image: $CI_REGISTRY_IMAGE/builder:$CI_COMMIT_REF_NAME-latest
  stage: 🏗️ build
  script:
    - make
  artifacts:
    paths:
      - rpms

# trigger this job by manually creating a pipeline with your P5 credentials
deploy:P5:
  stage: 🚀 deploy
  extends: .auto_devops_p5_dropbox_push
  rules:
    # omit if user did not supply P5 credentials
  - if: $P5_USER == null || $P5_PASS == null
    when: never
    # only when tagged
  - if: $PACKAGE_VER_PATCH || $CI_COMMIT_TAG
    when: manual
    allow_failure: false
  - when: never
  variables:
    LOCAL_FOLDER: rpms/python27
    DROPBOX_OS: cc7
    DROPBOX_ZONE: cms
    DROPBOX_NAME: hilton
    SSH_USERNAME: $P5_USER
    SSH_PASS: $P5_PASS
